name: CI/CD Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          cd frontend
          docker build -t tienda-frontend .
          docker tag tienda-frontend:latest ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest

      - name: Push Image to ECR
        run: |
          docker push ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest

      - name: Deploy Frontend in EC2
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_FRONTEND_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Frontend" \
            --parameters '{
              "commands": [
                "sudo docker stop tienda-frontend || true",
                "sudo docker rm tienda-frontend || true",
                "sudo docker image prune -af",
                "aws ecr get-login-password --region '${{ secrets.AWS_REGION }}' | sudo docker login --username AWS --password-stdin '${{ secrets.ECR_REGISTRY }}'",
                "sudo docker pull '${{ secrets.ECR_REPO_URL_FRONTEND }}:latest'",
                "sudo docker network create tienda-network || true",
                "sudo docker run -d --restart unless-stopped --name tienda-frontend --network tienda-network -p 80:80 -e BACKEND_URL='${{ secrets.BACKEND_URL }}' '${{ secrets.ECR_REPO_URL_FRONTEND }}:latest'",
                "sudo docker ps"
              ]
            }' \
            --region "${{ secrets.AWS_REGION }}"