name: CI/CD Tienda Perritos - Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build-push-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v5

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-session-token: IQoJb3JpZ2luX2VjEGsaCXVzLXdlc3QtMiJHMEUCIQCUgOdJ+XUR5rRyj992ilJYSQKhKnHZrniiP2T0WsFK1QIgSRSg5fMN43msHLpeeu331GLWrHslWQ+EQE3r2RRf954qrwIINBABGgwwNzY1MDI0NDcyODIiDCY5BkYUqCOoxMpbHCqMAu9chOB/3xMLEXzH8svXSq83wLyu+oI17kH1cMszzIKTuZnor96QePMf3MdNL43bgP3UjdFA6zsfHZisvMtazGT5pcwt3IPEiEOkBk13yfFh0+GtUkhXiMXDw2UEr5Fz7U//X1sS4P8vwyaNAgb5ZQMXSUGxsf7hFEjOvoHkEp0/gQ+gUmHUi9NLL/nGxj68UlxLyp5xTh0vXSfmeC5dN8Kkcaj9smFAfN/mmdwV6la9Iy7/NJnn6umoVXxsX3pGiqwDfoE89Q8v1MCDknOh7LBv3+oXDzAeqGRZX80jfSJxKcNg3s7H6ipkasTtIXKlSkszWt/2UoDnCOESeoL836TI6AFJruCM0OJVxLIwoe+N0AY6nQHtOZLQGZ9oC5T2rD91mQpdUYu1H0nBqGbrVY912YfyYm/FDT7XTv5EOB9sxmdID65nZerPyh3ktp4hVhN14kNKEbRJ55NN339wKxBbImw5n8QhAcn5hwOrwOKXV/ZfIRSmllT9pbUozrkUzVzJPZkC+39LEF5jrT0zd0VO4uhaF2/7G1iDynlHtR6E7PUsPsT9R/ax0DDghqmWdbQ3
          audience: sts.amazonaws.com
          output-env-credentials: true

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build imagen Frontend
        run: |
          cd frontend
          docker build -t tienda-perritos-frontend:latest .

      - name: Tag imagen Frontend
        run: |
          docker tag tienda-perritos-frontend:latest ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest
      - name: Push imagen Frontend
        run: |
          docker push tienda-perritos-frontend:latest ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest

      - name: Desplegar Frontend vía SSM
        run: |
              AWS_REGION="${{ secrets.AWS_REGION }}"
              ECR_REGISTRY="${{ secrets.ECR_REGISTRY }}"
              ECR_REPO_URL_FRONTEND="${{ secrets.ECR_REPO_URL_FRONTEND }}"
              EC2_BACKEND_URL="${{ secrets.EC2_BACKEND_URL }}"
              aws ssm send-command \
              --instance-ids "${{ secrets.EC2_FRONTEND_INSTANCE_ID }}" \
               --document-name "AWS-RunShellScript" \
               --comment "Actualizar tienda-perritos-frontend desde ECR" \
               --parameters '{
              "commands":[
                "set -e",
                "docker stop tienda-perritos-frontend || true",
                "docker rm tienda-perritos-frontend || true",
                "aws ecr get-login-password --region '${{ secrets.AWS_REGION }}' | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
                "docker pull ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest",
                "docker run -d --restart unless-stopped --name tienda-perritos-frontend -p 80:80 -e BACKEND_URL=${{ secrets.EC2_BACKEND_URL }} ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest"
              ]
              }' \
              --output text