name: CI/CD Tienda Perritos - Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build-push-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build imagen Frontend
        run: |
          cd frontend
          docker build -t tienda-perritos-frontend:latest .

      - name: Tag imagen Frontend
        run: |
          docker tag tienda-perritos-frontend:latest ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest
      - name: Push imagen Frontend
        run: |
          docker push tienda-perritos-frontend:latest ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest

      - name: Desplegar Frontend vía SSM
        run: |
              AWS_REGION="${{ secrets.AWS_REGION }}"
              ECR_REGISTRY="${{ secrets.ECR_REGISTRY }}"
              ECR_REPO_URL_FRONTEND="${{ secrets.ECR_REPO_URL_FRONTEND }}"
              EC2_BACKEND_URL="${{ secrets.EC2_BACKEND_URL }}"
              aws ssm send-command \
              --instance-ids "${{ secrets.EC2_FRONTEND_INSTANCE_ID }}" \
               --document-name "AWS-RunShellScript" \
               --comment "Actualizar tienda-perritos-frontend desde ECR" \
               --parameters '{
              "commands":[
                "set -e",
                "docker stop tienda-perritos-frontend || true",
                "docker rm tienda-perritos-frontend || true",
                "aws ecr get-login-password --region '${{ secrets.AWS_REGION }}' | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
                "docker pull ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest",
                "docker run -d --restart unless-stopped --name tienda-perritos-frontend -p 80:80 -e BACKEND_URL=${{ secrets.EC2_BACKEND_URL }} ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest"
              ]
              }' \
              --output text