name: CI/CD Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          cd backend
          docker build -t tienda-backend .
          docker tag tienda-backend:latest ${{ secrets.ECR_REPO_URL_BACKEND }}:latest

      - name: Push Image to ECR
        run: |
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:latest

      - name: Deploy Backend in EC2
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_BACKEND_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Backend" \
            --parameters '{
              "commands": [
                "sudo docker stop tienda-backend || true",
                "sudo docker rm tienda-backend || true",
                "sudo docker image prune -af",
                "aws ecr get-login-password --region '${{ secrets.AWS_REGION }}' | sudo docker login --username AWS --password-stdin '${{ secrets.ECR_REGISTRY }}'",
                "sudo docker pull '${{ secrets.ECR_REPO_URL_BACKEND }}:latest'",
                "sudo docker network create tienda-network || true",
                "sudo docker run -d --restart unless-stopped --name tienda-backend --network tienda-network -p 3001:3001 -e DB_HOST='${{ secrets.DB_HOST }}' -e DB_USER='${{ secrets.DB_USER }}' -e DB_PASSWORD='${{ secrets.DB_PASSWORD }}' -e DB_NAME='${{ secrets.DB_NAME }}' -e DB_PORT='${{ secrets.DB_PORT }}' '${{ secrets.ECR_REPO_URL_BACKEND }}:latest'",
                "sudo docker ps"
              ]
            }' \
            --region "${{ secrets.AWS_REGION }}"