name: Deploy to AWS ECR

on:
  push:
    branches: [ "main" ] # Se ejecuta cuando subes cambios a la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v4

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Iniciar sesión en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Construir, etiquetar y subir la imagen a Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: tu-nombre-de-repositorio-ecr # Cambia esto por el nombre en AWS
        IMAGE_TAG: latest
      run: |
        # Construye el contenedor Docker usando tu código fuente modificado
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # Sube la nueva versión a AWS ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG